# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7vx485tffg1761-2
set_property target_language Verilog [current_project]
set_property board xilinx.com:virtex7:vc707:1.1 [current_project]
set_param project.compositeFile.enableAutoGeneration 0

read_ip /home/ceca/litianshi/test_deinterleaver/test_deinterleaver.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /home/ceca/litianshi/test_deinterleaver/test_deinterleaver.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ceca/litianshi/test_deinterleaver/test_deinterleaver.data/wt [current_project]
set_property parent.project_dir /home/ceca/litianshi/test_deinterleaver [current_project]
synth_design -top fifo_generator_0 -part xc7vx485tffg1761-2 -mode out_of_context

rename_ref -prefix_all fifo_generator_0
write_checkpoint -noxdef fifo_generator_0.dcp
report_utilization -file fifo_generator_0_utilization_synth.rpt -pb fifo_generator_0_utilization_synth.pb
if { [catch {
  file copy -force /home/ceca/litianshi/test_deinterleaver/test_deinterleaver.runs/fifo_generator_0_synth_1/fifo_generator_0.dcp /home/ceca/litianshi/test_deinterleaver/test_deinterleaver.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.dcp
  write_verilog -force -mode synth_stub /home/ceca/litianshi/test_deinterleaver/test_deinterleaver.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_stub.v
  write_verilog -force -mode funcsim /home/ceca/litianshi/test_deinterleaver/test_deinterleaver.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_funcsim.v
  write_vhdl -force -mode funcsim /home/ceca/litianshi/test_deinterleaver/test_deinterleaver.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_funcsim.vhdl
} _RESULT ] } { 
  puts "Critical Warning: Unable to successfully create or copy supporting IP files."
}
